version: '3.8'
services:
  my-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
#    volumes:
#      - db:/var/lib/postgresql/data

  curreny:
    image: currency-image
    environment:
      DB_CONNECTION_USERNAME: postgres
      DB_CONNECTION_PASSWORD: postgres
      DB_NAME: currency
    ports:
      - '8090:8090'
    depends_on:
      - my-postgres
#volumes:
#  db:
#    driver: local