--liquibase formatted sql

--changeset Abbas:1
--create table valute_curs
create table valute_curs
(
    id                 bigint generated by default as identity
        primary key,
    created_by         varchar(50),
    created_date       timestamp,
    last_modified_by   varchar(50),
    last_modified_date timestamp,
    date               timestamp,
    description        varchar(255),
    is_active          boolean,
    is_deleted         boolean,
    name               varchar(255)
);

alter table valute_curs
    owner to postgres;


